- name: ArgoListener
  hosts: inb-fab2-apic1.cam.ciscolabs.com
  sources:
    - name: argo
  rules:
    - name: UpdateExtEPGs
      condition: event.meta.eda_event_stream_name == 'argocd'
      action:
        run_job_template:
          name: ManageExtEPGs
          organization: Default
          job_args:
            extra_vars:
              namespace: "{{ event.payload.namespace }}"
