# ACI playbook - Create Tenant prod including networking and contracts
---

- name: Create Tenant prod
  hosts: inb-fab2-apic1.cam.ciscolabs.com
  connection: local
  gather_facts: no

  vars:
    aci_login: &aci_login
      host: "{{ ansible_host }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password | default(omit) }}"
      private_key: "{{ aci_private_key | default(omit) }}"
      certificate_name: "{{ aci_certificate_name | default(omit) }}"
      validate_certs: "{{ aci_validate_certs }}"
      annotation: "orchestrator:ansible"
      state: present

  vars_files:
    - ./ext_epg_vars.yaml

  tasks:
    - name: Add a new ExtEpg
      cisco.aci.aci_l3out_extepg:
        <<: *aci_login
        tenant: "{{ tenant_name }}"
        l3out: "{{ l3out_name }}"
        name: "{{ ext_epg.name }}"

        state: present