apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.eda: ""
    notifications.argoproj.io/subscribe.on-deleted.eda: ""
    rule: egress
  name: egress-gateways
  namespace: openshift-gitops
spec:
  destination:
    namespace: ""
    server: https://cilium-bgp-1.cam.ciscolabs.com:6443
  project: default
  source:
    path: k8s/egress-gw
    repoURL: https://github.com/camrossi/aci-k8s-demo.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}