apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-reader
  namespace: default  # You can change this to any namespace you prefer

---

# Step 2: Create the ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-reader-role
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]

---

# Step 3: Create the ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-reader-binding
subjects:
- kind: ServiceAccount
  name: service-reader
  namespace: default  # This should match the namespace of your service account
roleRef:
  kind: ClusterRole
  name: service-reader-role
  apiGroup: rbac.authorization.k8s.io